name: EnoChecker Docker Image (nightly)

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: enochecker-dotnet

jobs:
  # Push image to GitHub Packages.
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2
      - run: ls -lah
      - name: Build image
        run: docker build . --file Dockerfile.EnoChecker --tag $IMAGE_NAME:nightly --progress=plain

      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u legofan --password-stdin

      - name: Push image to GitHub Container Registry
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          
          echo IMAGE_NAME=$IMAGE_NAME
          echo IMAGE_ID=$IMAGE_ID
          
          docker tag $IMAGE_NAME:nightly $IMAGE_ID:nightly
          docker push $IMAGE_ID:nightly
